name = "RationalApproximations"
uuid = "2c840ab3-4394-437e-91cb-e1d658a69763"
authors = ["William McLean <w.mclean@unsw.edu.au>"]
version = "0.1.0"

[deps]
GenericSVD = "01680d73-4ee2-5a08-a1aa-533608c188bb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
